---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:37017/test

---

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.2.0.28:1521:orcl
    username: Orclexi01
    password: Orclexi01
  jpa:
   show-sql: true   
---
spring:
  cloud:
    stream:
      bindings:
        paymentsChannel:
         binder: rabbit
         destination: newpayment.ms.exchange
         content-type: application/json
         group: qualcomm1    

---
spring:
  zipkin:
    base-url: http://localhost:8085
  sleuth:
    sampler:
      percentage: 1.0   
        


