---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/

---
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/EMPLOYEE_DB

---

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true      

---
spring:
  cloud:
    stream:
      bindings:
        paymentsChannel:
         binder: rabbit
         destination: newpayment.ms.exchange
         content-type: application/json
         group: qualcomm1    

---
spring:
  zipkin:
    base-url: http://localhost:8085
  sleuth:
    sampler:
      percentage: 1.0   
        


